WebApplication1/Models/QuartoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class QuartoViewModel
    {

        public int Id { get; set; }




    }
}

WebApplication1/Controllers/QuartosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BLL.reservas.bll;
using Data.reservas.model;

namespace WebApplication1.Controllers
{
    public class QuartosController : Controller
    {
        private ReservasModelDb db = new ReservasModelDb();
        private static HotelService hotelService = new HotelService();
        // GET: Quartos/Index/1
        public ActionResult Index(int id) // Aqui é o id do hotel
        {
            List<Quarto> quartos = hotelService.ListarQuartosHotel(id);
            return View(quartos);
        }

        // GET: Quartos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quarto quarto = db.Quarto.Find(id);
            if (quarto == null)
            {
                return HttpNotFound();
            }
            return View(quarto);
        }

        // GET: Quartos/Create
        public ActionResult Create()
        {
            ViewBag.HotelId = new SelectList(db.Hotel, "Id", "Nome");
            return View();
        }

        // POST: Quartos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,HotelId,Titulo,Descricao,Quantidade,MaximoOcupantes,ValorDiaria,ValorDiariaCrianca,DiariaPorOcupante")] Quarto quarto)
        {
            if (ModelState.IsValid)
            {
                db.Quarto.Add(quarto);
                db.SaveChanges();
                // /Quartos/Index/111
                return RedirectToAction("Index", new { Id = quarto.HotelId });
            }

            ViewBag.HotelId = new SelectList(db.Hotel, "Id", "Nome", quarto.HotelId);
            return View(quarto);
        }

        // GET: Quartos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quarto quarto = db.Quarto.Find(id);
            if (quarto == null)
            {
                return HttpNotFound();
            }
            ViewBag.HotelId = new SelectList(db.Hotel, "Id", "Nome", quarto.HotelId);
            return View(quarto);
        }

        // POST: Quartos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,HotelId,Titulo,Descricao,Quantidade,MaximoOcupantes,ValorDiaria,ValorDiariaCrianca,DiariaPorOcupante")] Quarto quarto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(quarto).State = EntityState.Modified;
                db.SaveChanges();
                // /Quartos/Index/111
                return RedirectToAction("Index", new { Id = quarto.HotelId });
            }
            ViewBag.HotelId = new SelectList(db.Hotel, "Id", "Nome", quarto.HotelId);
            return View(quarto);
        }

        // GET: Quartos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quarto quarto = db.Quarto.Find(id);
            if (quarto == null)
            {
                return HttpNotFound();
            }
            return View(quarto);
        }

        // POST: Quartos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Quarto quarto = db.Quarto.Find(id);
            db.Quarto.Remove(quarto);
            db.SaveChanges();
            // /Quartos/Index/111
            return RedirectToAction("Index", new { Id = quarto.HotelId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



    }
}

WebApplication1/Controllers/ReservaController.cs
using BLL.reservas.bll;
using Data.reservas.model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ReservaController : Controller
    {

        private ReservaViewModel reservaViewModel = new ReservaViewModel();
        private ReservasModelDb db = new ReservasModelDb();
        private static HotelService hotelService = new HotelService();
        // GET: Quartos/Index/1
       // public ActionResult Index() // Aqui é o id do hotel
        //{
            
        //}

       

        // No Post o valor selecionado do DropDownList}

        // será recebido no parametro clienteId

        public ActionResult Index()

        {

            //ViewBag.ReceberHotel = new SelectList(db.Hotel, "Id", "Nome");

            //ViewBag.ReceberQuarto = new SelectList(db.Quarto, "Id", "Descricao");
            var reserva = hotelService.listarReserva();
            return View(reserva);


        }
        
        public ActionResult Create()
        {
            
            Hotel hotel = db.Hotel.First();
           ViewBag.ReceberHotel = new SelectList(db.Hotel, "Id", "Nome");    


            ViewBag.ReceberQuarto = new SelectList(db.Quarto.Where(q => q.HotelId== hotel.Id).ToList(), "Id", "Descricao");

            // ViewBag.ReceberQuarto = new SelectList(db.Quarto.Where(prop=>prop.HotelId == prop.Id), "Id", "Descricao" );
            //LoadQuarto(hid);
            return View();
        }

        [HttpPost]
        public ActionResult Create(Reserva reserva)
        {

            reserva.Quarto = hotelService.buscarQuartoPorId(reserva.QuartoId);

            try
            {
                var teste = hotelService.listarReserva().Last();
                reserva.Id = teste.Id + 1;

            }
            catch { }
            hotelService.incluiReserva(reserva);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult BuscaQuartos(int id)
        {

            ViewBag.QuartoId = new SelectList(hotelService.ListarQuartosHotel(id), "Id", "Titulo");
            
            return View();
        }



        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reserva reserva = db.Reserva.Find(id);
            if (reserva == null)
            {
                return HttpNotFound();
            }
            return View(reserva);
        }



        public void LoadHotel(ReservaViewModel reservaViewModel)
        {
            
            ViewBag.LoadH = new SelectList(hotelService.ListarHoteis(), "Nome").ToList();
            var tem = ViewBag.LoadH;            

        }

        public ActionResult LoadQuarto(int id) {



   //         List<Quarto> quartos = hotelService.ListarQuartosHotel(id);

           ViewBag.ReceberQuarto = new SelectList(db.Quarto.Where(prop => prop.HotelId == id).ToList(), "Id", "Descricao");


            return PartialView();
           /* else {
                ViewBag.Traga = new SelectList(achou, "Id", "Descricao");
                return View();
            }*/

           
        }

        //[HttpPost]
       // public ActionResult TestCarregar(ReservaViewModel reservaViewModel)
       // {
       //     LoadHotel(reservaViewModel);
       //     //LoadQuarto(reservaViewModel);

        //    return View(reservaViewModel);
       // }

    }
}

WebApplication1/Views/Quartos/Create.cshtml
@model Data.reservas.model.Quarto

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Quarto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HotelId, "HotelId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HotelId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HotelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaximoOcupantes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaximoOcupantes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaximoOcupantes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorDiaria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorDiaria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorDiaria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorDiariaCrianca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorDiariaCrianca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorDiariaCrianca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiariaPorOcupante, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.DiariaPorOcupante)
                    @Html.ValidationMessageFor(model => model.DiariaPorOcupante, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication1/Views/Quartos/Delete.cshtml
@model Data.reservas.model.Quarto

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Quarto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Hotel.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hotel.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaximoOcupantes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaximoOcupantes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorDiaria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorDiaria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorDiariaCrianca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorDiariaCrianca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiariaPorOcupante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiariaPorOcupante)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Quartos/Details.cshtml
@model Data.reservas.model.Quarto

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Quarto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Hotel.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hotel.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaximoOcupantes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaximoOcupantes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorDiaria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorDiaria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorDiariaCrianca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorDiariaCrianca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiariaPorOcupante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiariaPorOcupante)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/Views/Quartos/Edit.cshtml
@model Data.reservas.model.Quarto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Quarto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.HotelId, "HotelId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HotelId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HotelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaximoOcupantes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaximoOcupantes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaximoOcupantes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorDiaria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorDiaria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorDiaria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorDiariaCrianca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorDiariaCrianca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorDiariaCrianca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiariaPorOcupante, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.DiariaPorOcupante)
                    @Html.ValidationMessageFor(model => model.DiariaPorOcupante, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication1/Views/Quartos/Index.cshtml
@model IEnumerable<Data.reservas.model.Quarto>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Hotel.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaximoOcupantes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ValorDiaria)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ValorDiariaCrianca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DiariaPorOcupante)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Hotel.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantidade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaximoOcupantes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ValorDiaria)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ValorDiariaCrianca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DiariaPorOcupante)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            @Html.ActionLink("Reservar", "Reserva", new { id = item.Id })
        </td>
    </tr>
}

</table>